# Generated by Django 5.2.6 on 2025-09-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessmentanalytics_assessmentgroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='blank_positions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='numeric_tolerance',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='matching_answers',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='numeric_answer',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='ordering_answers',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('identification', 'Identification'), ('enumeration', 'Enumeration'), ('essay', 'Essay')], max_length=20),
        ),
        migrations.DeleteModel(
            name='MatchingPair',
        ),
    ]
