# Generated by Django 5.2.6 on 2025-09-18 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_remove_question_blank_positions_and_more'),
    ]

    operations = [
    ]
