# Generated by Django 5.2.6 on 2025-09-10 03:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Activity Log', 'verbose_name_plural': 'User Activity Logs'},
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'User Settings', 'verbose_name_plural': 'User Settings'},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to=accounts.models.user_avatar_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us about yourself', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active_user',
            field=models.BooleanField(default=True, help_text='For soft delete'),
        ),
    ]
